version: '3'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    port:
      - {$PROMETHEUS}:9090
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  enviroexporter:
    build: .
    ports:
      - {$ENVIROEXPORTER}:8000
    container_name: enviroexporter
    restart: unless-stopped
    devices:
      - /dev/ttyAMA0
      - /dev/gpiomem
      - /dev/i2c-1

  homekit:
    build:
      context: .
      dockerfile: Dockerfile-homekit
    network_mode: host
    container_name: HomeKit
    restart: unless-stopped


  grafana:
    image: grafana/grafana:7.4.2
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    ports:
      - 3000:3000

volumes:
    prometheus_data: {}
