FROM golang:1.16

WORKDIR /go/src/app
RUN apt-get update && apt-get install git -y \
  && rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/sighmon/homekit-enviroplus .

RUN go get \
  && go build build homekit-enviroplus.go

CMD homekit-enviroplus.go -port=8000 -host=http://0.0.0.0 -sleep=10s
